name: PHPUnit Tests

on:
  push:
    branches:
      - '*' 
  pull_request:
    branches:
      - '*' 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.12'

    - name: Install dependencies
      run: composer install

    - name: Execute PHPUnit tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml
