name: PHPUnit Tests

on:
  pull_request:
    branches:
      - main 
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: senha123 
          MYSQL_DATABASE: liven_projeto 
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Execute PHPUnit tests
        run: phpunit --configuration phpunit.xml